import { Flex, Text } from "@radix-ui/themes";
import { BookMarkIcon, ReportIcon, ShareIcon, AIStar } from "@/app/assets";

export const SubHeader = ({ showAuthor }) => {
  return (
    <Flex justify="between" gap="5" mt="5" mb="6">
      <Flex gap="3">
        <Flex gap="3">
          <div
            className="flex justify-center items-center w-8 h-8"
            style={{
              background: "var(--BW-700, #414650)",
              padding: "4px",
              borderRadius: "8px",
            }}
          >
            <BookMarkIcon />
          </div>
          <div
            className="flex justify-center items-center w-8 h-8"
            style={{
              background: "var(--BW-700, #414650)",
              padding: "4px",
              borderRadius: "8px",
            }}
          >
            <ShareIcon />
          </div>
          <div
            className="flex justify-center items-center w-8 h-8"
            style={{
              background: "var(--BW-700, #414650)",
              padding: "4px",
              borderRadius: "8px",
            }}
          >
            <ReportIcon />
          </div>
        </Flex>
        {showAuthor && (
          <Flex align="center">
            <Text style={{ color: "var(--BW-100, #AAB2CF)" }} size="2">
              8min read
            </Text>
          </Flex>
        )}
      </Flex>
      {showAuthor && (
        <Flex align="center" gap="1">
          <AIStar />
          <Text
            size="2"
            style={{ color: "var(--Colors-Semantic-Warning-8, #E2A336)" }}
          >
            The list is generated by AI
          </Text>
        </Flex>
      )}
    </Flex>
  );
};
